### ISSUE TITLE
Base64 & .ico support. Also relative paths.

### ISSUE THREAD

**Issue by ghaschel** [ie-web-notifications/ie-web-notifications.github.io#11]
There is no support for base 64 png encoded files nor regular .ico files for icon display...
It would be nice to have.

Also, Image paths won't work if not in it's absolute form.

Thanks!

**Comment by ie-web-notifications** [comment]
Thanks for the report.

.ico files should work, e.g. http://google.com/favicon.ico, however there are some glitches with transparency, I will look into it. Do you know some particular unsupported ico file?

I will try to add the support of base64 encoded png and relative paths (not fully, only relative to the current page) in the next release.

**Comment by ghaschel** [comment]
Nevermind, the ico file I was using was corrupted. I should have tested with another one before posting here.

**Comment by ie-web-notifications** [comment]
Hi!
I have rewritten the drawing of native window, now it should support base64 encoded images and work much better with transparent images. Please find it in version _v0.8_.

The support of relative paths will be in the next release.

**Comment by ie-web-notifications** [comment]
I have added the support of relative paths for icon. Please find it in version v0.8.1.
