### ISSUE TITLE
Won't work if website is pinned to the taskbar.

### ISSUE THREAD

**Issue by ghaschel** [ie-web-notifications/ie-web-notifications.github.io#12]
Apparently "Notification" in window returns false if the website is pinned to the taskbar (dragging and droping it to the taskbar).

Running IE11 on Windows 7.

**Comment by ie-web-notifications** [comment]
Thanks for the report.
Unfortunately it is a user experience feature of Internet Explorer, BHOs are disabled for pinned sites.

> The pinned site window automatically starts an isolated instance of Internet Explorer that runs in a special mode (note that Browser Helper Objects and other toolbars are not enabled in this Internet Explorer mode)
> [Pinned Sites: Windows 7 Desktop Integration with Internet Explorer 9](https://msdn.microsoft.com/en-us/library/gg131029%28v=vs.85%29.aspx)
> 
> The reason Add-ons don't run on pinned sites is that we wanted to remove any non-site specific extension points (like toolbars and BHOs) from altering the original browsing experience created by the site.
> [User Experiences: Customizing Pinned Sites # comment](https://blogs.msdn.microsoft.com/ie/2010/09/17/user-experiences-customizing-pinned-sites/#comment-322961)
