### ISSUE TITLE
Notification is not hiding automatically

### ISSUE THREAD

**Issue by ambujkhanna** [ie-web-notifications/ie-web-notifications.github.io#16]
Hi,

I am facing 2 issues:
1) Notification is not hiding automatically
2) If my window/browser is not in the background then still I am receiving notification.

Can you help me on these issues?

Thanks in advance!!!!

**Comment by ie-web-notifications** [comment]
Hi!
Thanks for the report.

That's actually correct, the standard does not say that notifications should be automatically hidden or not shown when the tab is already active. It's the responsibility of notification initiator.

> 1) Notification is not hiding automatically

You can achieve it with several ways. E.g.:

``` JavaScript
var n = new Notification("It will be closed in 3 sec");
setTimeout(function(){this.close();}.bind(n), 3000);
```

However, there is an opportunity to miss the delivering of a notification to the user. Let's say the user has very active communication habit and receives a lot of notifications, the number of notifications shown at the same time can be limited according to current [standard](http://www.w3.org/TR/notifications/) and it is indeed limited by 3 at least in current versions of _Google Chrome_ and _IE Web Notifications_ for better UX. To avoid it one could use `onshow` handler and close the notification only after it has been actually shown, albeit `onshow` handler is considered as deprecated now.
The following code works only for IE Web Notifications

``` JavaScript
(new Notification("It will be closed in 3 sec")).onshown = function(){setTimeout(function(){this.close();}.bind(this), 3000);}
```

**Important note:** I'm sorry, there is a typo in the code for _IE Web Notifications_, it is called `onshown` not `onshow` (there is additional 'n' at the end).
Please also pay attention that `EventTarget` is not currently implemented in _IE Web Notifications_.

> 2) If my window/browser is not in the background then still I am receiving notification

You can try to use [Page Visibility API](https://www.w3.org/TR/page-visibility/), in particular `document.hidden`, `document.visibilityState` and listen when the value of the attribute changed by `document.addEventListener('visibilitychange', your-on-attribute-changed-handler)`. So when the document is active don't create notifications, however of course if the notification has been queued and the tab became inactive it will be shown.

**Comment by ambujkhanna** [comment]
Thanks. IE code is working but only issue i am facing is that if I am giving 5mins timeout in Chrome and Firefox then it's not taking but IE is taking. Firefox and chrome is taking max 15-20secs only.

**Comment by ie-web-notifications** [comment]
I can only recommend to double check the code, several minutes timeouts should work in both, in chrome and in firefox.

**Comment by ambujkhanna** [comment]
Thanks :)
