### ISSUE TITLE
What licence is the plugin

### ISSUE THREAD

**Issue by GregDThomas** [ie-web-notifications/ie-web-notifications.github.io#2]
What licence is the plugin published under?

Also, are there any plans to make the source available?

**Comment by ie-web-notifications** [comment]
Hello GregDThomas,
- There is actually no any licence.
  The software is provided "as is" without any express or implied warranty of any kind. In no event shall the author be liable for any damages, claim or other liability. Use it at your own risk as you want.
  The software shall be used to good.
-  There is a plan to open the source code in the future, but not now. If you have any question don't hesitate to ask here.

**Comment by GregDThomas** [comment]
Thanks for the update; is there anything we can do to help get the source released?

**Comment by boldwade** [comment]
Would this mean we could fork the project and provide a download for users that would be a more recognized URL?

**Comment by ie-web-notifications** [comment]
Yes, it will be possible to fork the project and actually I would like others to contribute, there is a lot of space for it.

Could you please explain what you understand under a _more recognized URL_?

**Comment by boldwade** [comment]
So right now, if I wanted someone to download the plugin, I would have to direct them to your site. Which to a customer, looks completely foreign and suspicious. I would like to host that plugin on my site (a more recognized url from the customers perspective). I would give complete credit to you for your work, I just want to host the code myself.

**Comment by ie-web-notifications** [comment]
The plugin is released under BSD 3-Clause License (https://opensource.org/licenses/BSD-3-Clause).

It means that one may use it in another projects according to the license terms.

> So right now, if I wanted someone to download the plugin, I would have to direct them to your site. Which to a customer, looks completely foreign and suspicious. I would like to host that plugin on my site (a more recognized url from the customers perspective). I would give complete credit to you for your work, I just want to host the code myself.

I have also updated the account name (renamed from `ukot` to `ie-web-notifications`) and got rid of path `/ie_web_notifications`. Meanwhile old URLs ([1](http://ukot.github.io), [2](http://ukot.github.io/ie_web_notifications)) with ukot are not dead, they simply redirect to https://ie-web-notifications.github.io/.
Could you please let me know if there is something else I can do to improve the trustworthiness of the welcome page?
