### ISSUE TITLE
IE 11 not available

### ISSUE THREAD

**Issue by sir-bsbaril** [ie-web-notifications/ie-web-notifications.github.io#21]
![image](https://cloud.githubusercontent.com/assets/17491778/22723355/86345d96-edf8-11e6-8533-1dc04adb3b68.png)

Why is it not available?

**Comment by maknesium** [comment]
I use the plugin with IE11 without problems. Just give it a try :)

**Comment by ie-web-notifications** [comment]
Have you installed the addon, restarted IE and allowed the extension?

**Comment by ie-web-notifications** [comment]
Since there is no respose, I suppose it works.
