### ISSUE TITLE
Border on notification

### ISSUE THREAD

**Issue by GregDThomas** [ie-web-notifications/ie-web-notifications.github.io#3]
There's no border on the notification; as the notification has a white background, this means that if it pops up on a screen with a white background (e.g. see the attached image) it's difficult to see - can you add a border to make it clearer?

Thanks.

![image](https://cloud.githubusercontent.com/assets/435813/9300373/266b5468-44bd-11e5-85a7-dcdfe77784f1.png)

(Other browser notifications, with border, can be seen at https://github.com/ttsvetko/HTML5-Desktop-Notifications)

**Comment by ie-web-notifications** [comment]
It's already done, but thanks a lot for the feedback.
It will be in the next release.

**Comment by ie-web-notifications** [comment]
Here it is, sorry for high DPI screen.
![screenshot-with-border-and-shadow](https://cloud.githubusercontent.com/assets/11330865/9317411/a3508416-453b-11e5-9274-39d0d0237cd2.png)

**Comment by GregDThomas** [comment]
Very nice looking, thanks :)
