### ISSUE TITLE
List of approved sites

### ISSUE THREAD

**Issue by GregDThomas** [ie-web-notifications/ie-web-notifications.github.io#4]
Chrome (by clicking on the bell in the taskbar, and then clicking on the cog) offers a mechanism by which it's possible to view sites that have been approved for a notification - and probably Firefox/Safari too. 

Can you add such a facility?

Thanks

**Comment by ie-web-notifications** [comment]
Yes, sure, it will be added, but likely not in the upcoming release, sorry.
So far, one can find it in `C:\Users\%username%\AppData\LocalLow\IE Web Notifications\db`.

**Comment by ie-web-notifications** [comment]
A simple settings window with the list of web sites is available on right-click on the notification window.
![screenshot-with-settings-window](https://cloud.githubusercontent.com/assets/11330865/9599389/e01fe0e0-5093-11e5-882f-19f49d7a7846.png)
Thanks.
