### ISSUE TITLE
Neither installer nor the plugin files are signed

### ISSUE THREAD

**Issue by guyshalom** [ie-web-notifications/ie-web-notifications.github.io#6]
Hi,

Great plugin! 
Solved us a big issue of cross-browser support :)
I want to use it for customers where I implement my SaaS services.
Can you publish a verified/signed installer/plugin..?
I also read you might open-source it - Can we help in any way?

Thanks,
Guy.

**Comment by ie-web-notifications** [comment]
Thanks a lot for the response.

I plan to sign the msi package as well as binaries however it takes some time to obtain the certificate.

**Comment by guyshalom** [comment]
Great news - will follow for an update :)
Good luck!
And please, don't hesitate to ping us if we can help in any way.

Thanks again,
Guy.

**Comment by ie-web-notifications** [comment]
I will close this issue after signing.

**Comment by GregDThomas** [comment]
Certum offer cheap + quick code signing cert's for open source software - http://certum.eu/certum/cert,offer_code_signing.xml (not that I've used them, though)
