### ISSUE TITLE
Open Source

### ISSUE THREAD

**Issue by ajbaj** [ie-web-notifications/ie-web-notifications.github.io#7]
HI

When do you plan to make it open source.  This is the kind of functionality I need to add in my application but with some more tweaks.

**Comment by yapsunny** [comment]
Echoing the request above, would like to have access to the source code.  I do not intend to change anything.

**Comment by JeffLeFoll** [comment]
Hello, 
I need to have notification working on IE11 but I can't use third party plugin unless they are open source so that we can perform code review and audit.

Is it possible to have acces to the source code ?

Thank you

**Comment by mattytb** [comment]
Any Joy with this, would love to use this but cannot without full disclosure.

**Comment by maknesium** [comment]
I chime in the request to opensource this module. I would love to use the web notifications for my current project and I neet to support Internet Explorer.

Any chance the code will be released as opensource?

**Comment by ie-web-notifications** [comment]
Yes, it will be released "soon". I have already prepared the code to have it published. However firstly I would like to clarify one license question.
So basically it's ready, I'm just waiting for the response from third party, it will take some time, please don't worry regarding it.

**Comment by maknesium** [comment]
Thank you very much for letting us know. I keep my fingers crossed. Trough open sourcing this plugin, web notifications can be used in enterprise software where the company (still) uses internet explorer. Since it's open source, companies can take a look and verify nothing "evil" is hiding somewhere :)

**Comment by ie-web-notifications** [comment]
The source code is avaiable at https://github.com/ie-web-notifications/ie-web-notifications under BSD 3-Clause License (https://opensource.org/licenses/BSD-3-Clause) 🎉 .

Could you please let me know about anything "evil" or vulnerable there as well as about bugs and possible issues?

One may use it in another projects according to the license terms.

Pull requests are very welcome.

If you have some questions feel free to create an issue with it.

Thanks for waiting.

**Comment by GregDThomas** [comment]
Thank you - for going to the effort to produce the plugin in the first place, and also for the ongoing bug fixes, and now for making it Open Source.

**Comment by ajbaj** [comment]
Thanks a lot

**Comment by maknesium** [comment]
Great!! Thank you for releasing the source code!
