### ISSUE TITLE
UI Changes

### ISSUE THREAD

**Issue by guyshalom** [ie-web-notifications/ie-web-notifications.github.io#8]
Hi There Again,

2 UI requests :)
1. Is it possible to make the Notification message a bit bigger like in Chrome/Firefox?
   ![image](https://cloud.githubusercontent.com/assets/14110196/10024429/e1b740f6-615f-11e5-988e-ec7fd570b79a.png)
2. In addition, will it be possible to make the logo image size same width & height (currently it's 60_58 while in Chrome/Firefox it's 40_40/46*46))

These 2 changes will allow us to use same text length and picture resolutions.

Thanks again - great Plugin!

Guy,
SoluPix,

**Comment by ie-web-notifications** [comment]
Hi!

Thanks for the report. I've increased the size of the window as well as changed the icon size to 40x40 device independent pixels, though I had not completely got the second paragraph.

Best regards,

**Comment by guyshalom** [comment]
Hi,

Thanks a lot.

Second paragraph wat talking about the icon ratio that was fixed as well  :)
The website probably removed some asterix chars from the text I wrote, what I wrote was:
"In addition, will it be possible to make the logo image size same width & height (currently it's 60X58 while in Chrome/Firefox it's 40X40/46X46)"

btw, We have encountered a wired problem insome PCs where the add-on crashes and re-opens over and over again when I try to load internet explorer.
It happens even with no homepage or specific website.
I can see a new ie_webnotifications process launches in task manager after every crash error messgae aproval. Your only way out is to end iexplore.exe process
This situation isn't solved even after a full restart and basically kills the explorer untill you remove the add-on.
Have you seen it before? Do you have a solution for that?

Thanks,
Guy

**Comment by ie-web-notifications** [comment]
I've created an issue about the crash, see #9.
