### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by ie-web-notifications** [ie-web-notifications/ie-web-notifications.github.io#9]
@guyshalom wrote in #8:

> btw, We have encountered a wired problem insome PCs where the add-on crashes and re-opens over and over again when I try to load internet explorer.
>  It happens even with no homepage or specific website.
>  I can see a new ie_webnotifications process launches in task manager after every crash error messgae aproval. Your only way out is to end iexplore.exe process
>  This situation isn't solved even after a full restart and basically kills the explorer untill you remove the add-on.
>  Have you seen it before? Do you have a solution for that?

**Comment by ie-web-notifications** [comment]
Could you give a bit of additional information about the OS, IE version, other addons installed as well as the version of IE Web Notifications addon?

**Comment by guyshalom** [comment]
Windows 7 x64 SP1, 
IE 11, Version: 110.09600.18015, Update versions:11.0.23
No additional add-ons installed.
Uninstall & reinstall seems solves it.

**Comment by ie-web-notifications** [comment]
I've checked on this configuration, it seems working.
Thanks a lot for the report. Feel free to reopen the issue if you can reproduce it.
